apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-3
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-3
  template:
    metadata:
      labels:
        app: guestbook-3
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          name: guestbook-3
          ports:
            - containerPort: 80
