apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guessbook-app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: k8s/prod/app1
    repoURL: "https://github.com/wt-854/argocd-app-of-app-demo.git"
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
