apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: prod
    server: "https://kubernetes.default.svc"
  source:
    path: k8s/prod/helm-guestbook
    repoURL: "https://github.com/wt-854/argocd-app-of-app-demo.git"
    targetRevision: master
    helm:
      valueFiles:
        - values-production.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
