apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: app-of-apps-prod
  name: app-of-apps-prod
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-apps/child/prod
    repoURL: https://gitlab.com/wt-854/argocd-example-apps.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true
