apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-guessbook-app2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: k8s/staging/app2
    repoURL: "https://gitlab.com/wt-854/argocd-example-apps.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
