apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-guessbook-app3
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: k8s/staging/app3
    repoURL: "https://github.com/wt-854/argocd-app-of-app-demo.git"
    targetRevision: master
  syncPolicy:
    ## Comment out auto sync to test behaviour
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
